function [allData, scenario, sensor] = generateSensorData()
%generateSensorData - Returns sensor detections
%    allData = generateSensorData returns sensor detections in a structure
%    with time for an internally defined scenario and sensor suite.
%
%    [allData, scenario, sensors] = generateSensorData optionally returns
%    the drivingScenario and detection generator objects.

% Generated by MATLAB(R) 24.1 (R2024a) and Automated Driving Toolbox 24.1 (R2024a).
% Generated on: 22-Aug-2024 06:53:30

% Create the drivingScenario object and ego car
[scenario, egoVehicle] = createDrivingScenario;

% Create all the sensors
sensor = createSensor(scenario);

allData = struct('Time', {}, 'ActorPoses', {}, 'ObjectDetections', {}, 'LaneDetections', {}, 'PointClouds', {}, 'INSMeasurements', {});
running = true;
while running

    % Generate the target poses of all actors relative to the ego vehicle
    poses = targetPoses(egoVehicle);
    time  = scenario.SimulationTime;

    % Generate detections for the sensor
    laneDetections = [];
    ptClouds = [];
    insMeas = [];
    [objectDetections, isValidTime] = sensor(poses, time);
    numObjects = length(objectDetections);
    objectDetections = objectDetections(1:numObjects);

    % Aggregate all detections into a structure for later use
    %if isValidTime
        allData(end + 1) = struct( ...
            'Time',       scenario.SimulationTime, ...
            'ActorPoses', actorPoses(scenario), ...
            'ObjectDetections', {objectDetections}, ...
            'LaneDetections', {laneDetections}, ...
            'PointClouds',   {ptClouds}, ... %#ok<AGROW>
            'INSMeasurements',   {insMeas}); %#ok<AGROW>
    %end

    % Advance the scenario one time step and exit the loop if the scenario is complete
    running = advance(scenario);
end

% Restart the driving scenario to return the actors to their initial positions.
restart(scenario);

% Release the sensor object so it can be used again.
release(sensor);

%%%%%%%%%%%%%%%%%%%%
% Helper functions %
%%%%%%%%%%%%%%%%%%%%

% Units used in createSensors and createDrivingScenario
% Distance/Position - meters
% Speed             - meters/second
% Angles            - degrees
% RCS Pattern       - dBsm

function sensor = createSensor(scenario)
% createSensors Returns all sensor objects to generate detections

% Assign into each sensor the physical and radar profiles for all actors
profiles = actorProfiles(scenario);
sensor = visionDetectionGenerator('SensorIndex', 1, ...
    'SensorLocation', [3.7 0], ...
    'MaxRange', 100, ...
    'DetectorOutput', 'Objects only', ...
    'Intrinsics', cameraIntrinsics([1814.81018227767 1814.81018227767],[320 240],[480 640]), ...
    'ActorProfiles', profiles);

function [scenario, egoVehicle] = createDrivingScenario
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-1 0.12 0;
    13.28 0.12 0;
    32.44 4.59 0;
    56.54 4.75 0;
    63.2 4.7 0;
    90.7 6.7 0;
    106.2 5.3 0;
    136.4 -1.6 0;
    167.7 2.1 0;
    187.3 13.3 0;
    208.3 14.4 0;
    232.1 8.3 0;
    254.5 1.6 0;
    266.9 -11.2 0;
    268.7 -38.6 0;
    254.9 -70.6 0;
    240.6 -95.5 0;
    216.8 -106.5 0;
    193 -103.3 0;
    163.1 -99.1 0;
    120.1 -96.9 0;
    85.6 -94.8 0;
    50.1 -89.8 0;
    34.8 -80.9 0;
    23.1 -68.5 0;
    8.1 -42.2 0;
    -1.8 -18.4 0;
    -1 0.12 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-0.2 -0.9 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [0.799999999999999 -0.5 0;
    9.3 -0.0999999999999996 0;
    32.2 3.1 0;
    70.5 7.1 0;
    115 2.7 0;
    149.3 0.0999999999999996 0;
    164 1.5 0;
    176.8 5.6 0;
    181.6 9.2 0;
    187.4 11.7 0;
    193.3 14 0;
    210 13.3 0;
    223.9 9.8 0;
    236 8.4 0;
    244.5 4.4 0;
    255.1 -0.199999999999999 0;
    263.3 -6.9 0;
    269 -19.7 0;
    265.8 -44.3 0;
    253.4 -69.1 0;
    244.1 -87.6 0;
    231.7 -99.4 0;
    216 -104.3 0;
    204.3 -105.4 0;
    186.9 -102.6 0;
    168.8 -98.7 0;
    143.9 -97.2 0;
    123.6 -94.4 0;
    90.5 -94 0;
    58.5 -92.3 0;
    39.3 -82.7 0;
    21.2 -63.1 0;
    4.2 -29 0;
    -2.9 -12.6 0;
    10.2 0.5 0;
    9.8 0.5 0];
speed = [15;15;15;15;15;15;15;15;15;30;30;30;30;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15;15];
trajectory(egoVehicle, waypoints, speed);




